"""add_map_uniqueness_constraint

Revision ID: 06575528f92e
Revises: fc1ddb77ce62
Create Date: 2026-01-22 00:02:23.517165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '06575528f92e'
down_revision: Union[str, Sequence[str], None] = 'fc1ddb77ce62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_map_atlas_name', 'map', ['atlas_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_map_atlas_name', 'map', type_='unique')
    # ### end Alembic commands ###
