"""Add access policy

Revision ID: 1ea77b3ee1bb
Revises: 06575528f92e
Create Date: 2026-01-22 16:18:56.244851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1ea77b3ee1bb'
down_revision: Union[str, Sequence[str], None] = '06575528f92e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atlas', sa.Column('access_policy', sa.Enum('standard', 'public', name='accesspolicy'), server_default=sa.text("'standard'"), nullable=False))
    op.add_column('map', sa.Column('access_policy', sa.Enum('standard', 'public', name='accesspolicy'), server_default=sa.text("'standard'"), nullable=False))
    op.add_column('team', sa.Column('access_policy', sa.Enum('standard', 'public', name='accesspolicy'), server_default=sa.text("'standard'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'access_policy')
    op.drop_column('map', 'access_policy')
    op.drop_column('atlas', 'access_policy')
    # ### end Alembic commands ###
