"""
Revision ID: 1ef4e0577b36
Revises: 06575528f92e
Create Date: 2026-01-23 03:07:49.675424

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ef4e0577b36"
down_revision: Union[str, Sequence[str], None] = "06575528f92e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    access_policy_type = sa.Enum("standard", "public", name="accesspolicy")
    access_policy_type.create(op.get_bind())

    op.add_column(
        "atlas",
        sa.Column(
            "access_policy",
            access_policy_type,
            server_default=sa.text("'standard'"),
            nullable=False,
        ),
    )
    op.add_column(
        "map",
        sa.Column(
            "access_policy",
            access_policy_type,
            server_default=sa.text("'standard'"),
            nullable=False,
        ),
    )
    op.add_column(
        "team",
        sa.Column(
            "access_policy",
            access_policy_type,
            server_default=sa.text("'standard'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team", "access_policy")
    op.drop_column("map", "access_policy")
    op.drop_column("atlas", "access_policy")

    access_policy_type = sa.Enum(name="accesspolicy")
    access_policy_type.drop(op.get_bind())
    # ### end Alembic commands ###
