"""Refactor Map-Atlas relationship to One-to-Many

Revision ID: 40327966e609
Revises: 145bc63ce314
Create Date: 2026-01-19 20:01:42.880039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40327966e609'
down_revision: Union[str, Sequence[str], None] = '145bc63ce314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atlasmaplink')
    op.add_column('map', sa.Column('atlas_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'map', 'atlas', ['atlas_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'map', type_='foreignkey')
    op.drop_column('map', 'atlas_id')
    op.create_table('atlasmaplink',
    sa.Column('atlas_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('map_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['atlas_id'], ['atlas.id'], name=op.f('fk_atlasmaplink_atlas_id_atlas')),
    sa.ForeignKeyConstraint(['map_id'], ['map.id'], name=op.f('fk_atlasmaplink_map_id_map')),
    sa.PrimaryKeyConstraint('atlas_id', 'map_id', name=op.f('pk_atlasmaplink'))
    )
    # ### end Alembic commands ###
