"""add_audit_columns

Revision ID: fc1ddb77ce62
Revises: 40327966e609
Create Date: 2026-01-21 23:55:55.229033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc1ddb77ce62'
down_revision: Union[str, Sequence[str], None] = '40327966e609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atlas', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('atlas', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('atlas', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('atlas', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_atlas_name'), 'atlas', ['name'], unique=True)
    op.create_foreign_key(None, 'atlas', 'user', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'atlas', 'user', ['created_by_id'], ['id'])
    op.drop_constraint(op.f('fk_atlasteamlink_team_id_team'), 'atlasteamlink', type_='foreignkey')
    op.drop_constraint(op.f('fk_atlasteamlink_atlas_id_atlas'), 'atlasteamlink', type_='foreignkey')
    op.create_foreign_key(None, 'atlasteamlink', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'atlasteamlink', 'atlas', ['atlas_id'], ['id'], ondelete='CASCADE')
    op.add_column('map', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('map', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('map', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('map', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.alter_column('map', 'atlas_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_map_atlas_id_atlas'), 'map', type_='foreignkey')
    op.create_foreign_key(None, 'map', 'atlas', ['atlas_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'map', 'user', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'map', 'user', ['updated_by_id'], ['id'])
    op.add_column('team', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('team', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('team', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'team', 'user', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'team', 'user', ['updated_by_id'], ['id'])
    op.drop_constraint(op.f('fk_userteamlink_user_id_user'), 'userteamlink', type_='foreignkey')
    op.drop_constraint(op.f('fk_userteamlink_team_id_team'), 'userteamlink', type_='foreignkey')
    op.create_foreign_key(None, 'userteamlink', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'userteamlink', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userteamlink', type_='foreignkey')
    op.drop_constraint(None, 'userteamlink', type_='foreignkey')
    op.create_foreign_key(op.f('fk_userteamlink_team_id_team'), 'userteamlink', 'team', ['team_id'], ['id'])
    op.create_foreign_key(op.f('fk_userteamlink_user_id_user'), 'userteamlink', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column('team', 'updated_by_id')
    op.drop_column('team', 'updated_at')
    op.drop_column('team', 'created_at')
    op.drop_column('team', 'created_by_id')
    op.drop_constraint(None, 'map', type_='foreignkey')
    op.drop_constraint(None, 'map', type_='foreignkey')
    op.drop_constraint(None, 'map', type_='foreignkey')
    op.create_foreign_key(op.f('fk_map_atlas_id_atlas'), 'map', 'atlas', ['atlas_id'], ['id'])
    op.alter_column('map', 'atlas_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('map', 'updated_by_id')
    op.drop_column('map', 'updated_at')
    op.drop_column('map', 'created_at')
    op.drop_column('map', 'created_by_id')
    op.drop_constraint(None, 'atlasteamlink', type_='foreignkey')
    op.drop_constraint(None, 'atlasteamlink', type_='foreignkey')
    op.create_foreign_key(op.f('fk_atlasteamlink_atlas_id_atlas'), 'atlasteamlink', 'atlas', ['atlas_id'], ['id'])
    op.create_foreign_key(op.f('fk_atlasteamlink_team_id_team'), 'atlasteamlink', 'team', ['team_id'], ['id'])
    op.drop_constraint(None, 'atlas', type_='foreignkey')
    op.drop_constraint(None, 'atlas', type_='foreignkey')
    op.drop_index(op.f('ix_atlas_name'), table_name='atlas')
    op.drop_column('atlas', 'updated_by_id')
    op.drop_column('atlas', 'updated_at')
    op.drop_column('atlas', 'created_at')
    op.drop_column('atlas', 'created_by_id')
    # ### end Alembic commands ###
